#ifndef BOUNDS_PINS_H
# define BOUNDS_PINS_H

# define X_RIGHT_EYE_PIN 3
# define Y_RIGHT_EYE_PIN 5
# define X_LEFT_EYE_PIN 6
# define Y_LEFT_EYE_PIN 9
# define MOUTH_PIN 10
# define ROLL_NECK_PIN 11
# define YAW_NECK_PIN 13

# define RIGHT_EYE_X_BOUND_MIN 20
# define RIGHT_EYE_X_BOUND_MAX 100
# define RIGHT_EYE_Y_BOUND_MIN 75
# define RIGHT_EYE_Y_BOUND_MAX 150
# define LEFT_EYE_X_BOUND_MIN 55
# define LEFT_EYE_X_BOUND_MAX 130
# define LEFT_EYE_Y_BOUND_MIN 60
# define LEFT_EYE_Y_BOUND_MAX 125
# define MOUTH_BOUND_MIN 75
# define MOUTH_BOUND_MAX 180
# define ROLL_BOUND_MIN 70
# define ROLL_BOUND_MAX 100
# define YAW_BOUND_MIN 50
# define YAW_BOUND_MAX 132

#endif